# Generated by Django 3.0.5 on 2020-05-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20200503_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzainfo',
            name='image_url',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='pizza.Ingredient'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_ingredients', to='pizza.PizzaInfo'),
        ),
    ]
