# Generated by Django 3.0.5 on 2020-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20200503_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzainfo',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
